# -*- coding: utf-8 -*-
"""CIFAR-10(SAM).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OiyQF8ZhCPsXXmHPjBteT4GRWpGLJIuH
"""

import torch
import torch.nn as nn
import torchvision.datasets as datasets
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import time

device = 'cuda' if torch.cuda.is_available() else 'cpu'

from torch.utils.data import random_split
raw_train_dataset = datasets.CIFAR10('/CIFAR10', True, transforms.ToTensor(), download=True)
test_dataset = datasets.CIFAR10('/CIFAR10', False, transforms.ToTensor(), download=True)

total_size = len(raw_train_dataset)
val_size = int(total_size * 0.1)
train_size = total_size - val_size

generator = torch.Generator().manual_seed(77)
train_dataset, val_dataset = random_split(raw_train_dataset, [train_size, val_size], generator)

epochs = 30
batch_size = 128

# train_iteration = len(train_dataset) // batch_size
# val_iteration = len(val_dataset) // batch_size
# test_iteration = len(test_dataset) // batch_size

# print(train_dataset.data.shape)
# print(val_dataset.data.shape)
print(test_dataset.data.shape)

train_data_loader = torch.utils.data.DataLoader(train_dataset, batch_size, True)
val_data_loader = torch.utils.data.DataLoader(val_dataset, batch_size, False)
test_data_loader = torch.utils.data.DataLoader(test_dataset, batch_size, False)

class BasicBlock(nn.Module):
  def __init__(self, in_channels, out_channels, stride=1):
    super().__init__()

    self.conv1 = nn.Conv2d(in_channels, out_channels, 3, stride, 1, bias=False)
    self.bn1 = nn.BatchNorm2d(out_channels)
    self.relu = nn.ReLU()

    self.conv2 = nn.Conv2d(out_channels, out_channels, 3, 1, 1, bias=False)
    self.bn2 = nn.BatchNorm2d(out_channels)

    self.shortcut = nn.Sequential()

    if in_channels != out_channels or stride != 1:
      self.shortcut = nn.Sequential(
        nn.Conv2d(in_channels, out_channels, 1, stride, bias=False),
        nn.BatchNorm2d(out_channels)
      )

  def forward(self, x):
    identity = self.shortcut(x)

    x = self.conv1(x)
    x = self.bn1(x)
    x = self.relu(x)

    x = self.conv2(x)
    x = self.bn2(x)
    x += identity
    x = self.relu(x)

    return x

class ResNet(nn.Module):
  def __init__(self, block, num_blocks_arr, num_classes=10):
    super().__init__()
    self.conv1 = nn.Sequential(
        nn.Conv2d(3, 16, 3, 1, 1, bias=False),
        nn.BatchNorm2d(16),
        nn.ReLU()
    )
    self.in_channels = 16
    self.conv2 = self._make_layer(block, 16, num_blocks_arr[0], 1)
    self.conv3 = self._make_layer(block, 32, num_blocks_arr[1], 2)
    self.conv4 = self._make_layer(block, 64, num_blocks_arr[2], 2)
    # self.avgpool = nn.AvgPool2d(8)
    self.avgpool = nn.AdaptiveAvgPool2d((1,1))
    self.flatten = nn.Flatten()
    # self.fc = nn.Linear(8*8*64, num_classes)
    self.fc = nn.Linear(64, num_classes)

    self._init_layer()

  def _make_layer(self, block, out_channels, num_blocks, stride=1):
    strides = [stride] + [1] * (num_blocks-1)
    layers = []
    for stride in strides:
      layers.append(BasicBlock(self.in_channels, out_channels, stride))
      self.in_channels = out_channels
    return nn.Sequential(*layers)


  def _init_layer(self):
    for m in self.modules():
      if isinstance(m, nn.Conv2d):
        nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
      elif isinstance(m, (nn.BatchNorm2d, nn.GroupNorm)):
        nn.init.constant_(m.weight, 1)
        nn.init.constant_(m.bias, 0)


  def forward(self, x):
    x = self.conv1(x)
    x = self.conv2(x)
    x = self.conv3(x)
    x = self.conv4(x)

    x = self.avgpool(x)
    x = self.flatten(x)
    x = self.fc(x)

    return x

model = ResNet(BasicBlock, [3, 3, 3]).to(device)

from torch.optim import Muon

criterion = torch.nn.CrossEntropyLoss().to(device)
# optimizer = torch.optim.AdamW(model.parameters(), weight_decay=1e-3)

class SAM(torch.optim.Optimizer):
  def __init__(self, params, base_optimizer, rho=0.05, **kwargs):

    defaults = dict(rho=rho, **kwargs)
    super(SAM, self).__init__(params, defaults)

    self.base_optimizer = base_optimizer(self.param_groups, **kwargs)
    self.param_groups = self.base_optimizer.param_groups

  @torch.no_grad()
  def first_step(self, zero_grad=False):
    """가장 가파른 오르막 방향으로 파라미터를 이동시킵니다 (epsilon 계산)."""
    grad_norm = self._grad_norm()
    for group in self.param_groups:
      scale = group["rho"] / (grad_norm + 1e-12)

      for p in group["params"]:
        if p.grad is None: continue
        # 파라미터별 변화량 계산: e_w = (rho / ||g||) * g
        e_w = p.grad * scale.to(p)
        p.add_(e_w)  # 파라미터를 오르막으로 이동
        self.state[p]["e_w"] = e_w # 나중에 복구하기 위해 저장

    if zero_grad: self.zero_grad()

  @torch.no_grad()
  def second_step(self, zero_grad=False):
    """이동했던 파라미터를 복구하고, 새로운 기울기로 실제 업데이트를 수행합니다."""
    for group in self.param_groups:
      for p in group["params"]:
        if p.grad is None: continue
        p.sub_(self.state[p]["e_w"])  # 원래 위치로 복구

    self.base_optimizer.step()  # 실제 업데이트 실행
    if zero_grad: self.zero_grad()

  def _grad_norm(self):
    """전체 파라미터의 L2 Norm을 계산합니다."""
    shared_device = self.param_groups[0]["params"][0].device
    norm = torch.norm(
      torch.stack([
          p.grad.norm(p=2).to(shared_device)
          for group in self.param_groups for p in group["params"]
          if p.grad is not None
          ]),
      p=2)
    return norm

optimizer = SAM(model.parameters(), torch.optim.SGD, rho = 0.05, lr= 0.1, momentum=0.9, weight_decay=1e-4)

scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, 'min', 0.1, 5, 1e-4)

train_loss_list = []
val_loss_list = []
# test_loss_list = []
train_acc_list = []
val_acc_list = []
# test_acc_list = []

start = time.time()
tmp = time.time()

for epoch in range(epochs):
  train_loss = 0
  val_loss = 0
  # test_loss = 0
  train_correct = 0
  val_correct = 0
  # test_correct = 0

  model.train()

  for X,Y in train_data_loader:
    X = X.to(device)
    Y = Y.to(device)

    optimizer.zero_grad()
    hypothesis = model(X)
    loss = criterion(hypothesis, Y)
    loss.backward()
    optimizer.first_step()

    criterion(model(X), Y).backward()
    optimizer.second_step()

  model.eval()

  with torch.no_grad():

    train_iteration = 0
    for X,Y in train_data_loader:
      X = X.to(device)
      Y = Y.to(device)

      hypothesis = model(X)
      loss = criterion(hypothesis, Y)
      train_correct += (torch.argmax(hypothesis, 1) == Y).sum().item()
      train_loss += loss
      train_iteration += 1

    val_iteration = 0
    for X,Y in val_data_loader:
      X = X.to(device)
      Y = Y.to(device)

      hypothesis = model(X)
      loss = criterion(hypothesis, Y)
      val_correct += (torch.argmax(hypothesis, 1) == Y).sum().item()
      val_loss += loss
      val_iteration += 1

    # test_iteration = 0
    # for X,Y in test_data_loader:
    #   X = X.to(device)
    #   Y = Y.to(device)

    #   hypothesis = model(X)
    #   loss = criterion(hypothesis, Y)
    #   test_correct += (torch.argmax(hypothesis, 1) == Y).sum().item()
    #   test_loss += loss
    #   test_iteration += 1

    avg_train_loss = train_loss / train_iteration
    avg_val_loss = val_loss / val_iteration
    # avg_test_loss = test_loss / test_iteration

  scheduler.step(avg_val_loss)

  train_loss_list.append(avg_train_loss.item())
  val_loss_list.append(avg_val_loss.item())
  # test_loss_list.append(avg_test_loss.item())
  train_acc_list.append(train_correct/len(train_dataset)*100)
  val_acc_list.append(val_correct/len(val_dataset)*100)
  # test_acc_list.append(test_correct/len(test_dataset)*100)

  # print(f"Epoch: {epoch+1:04d}, Training Loss: {avg_train_loss:.6f}, Validation Loss: {avg_val_loss:.6f}, Test Loss: {avg_test_loss:.6f}")
  print(f"Epoch: {epoch+1:04d}, Training Loss: {avg_train_loss:.6f}, Validation Loss: {avg_val_loss:.6f}")
  print(f"Learning Time: {time.time()-tmp:.4f}s")
  tmp = time.time()

total_time = time.time() - start
print(f"Total Learning Time: {int(total_time//60):d}m {total_time%60:.4f}s")

from matplotlib import axes

epoch = range(1, epochs+1)
fig, axes = plt.subplots(1, 2, figsize=(12,5))

fig.suptitle('ResNet9(SAM+SGD) on CIFAR-10')

axes[0].plot(epoch, train_loss_list, label='train loss')
axes[0].plot(epoch, val_loss_list, label='val loss')
# axes[0].plot(epoch, test_loss_list, label='test loss')

# axes[0].set_title('Train & Validation & Test loss')
axes[0].set_title('Train & Validation loss')
axes[0].set_xlabel('epoch')
axes[0].set_ylabel('loss')
axes[0].legend()
axes[0].grid()

train_err_list = []
val_err_list = []
# test_err_list = []

for i in range(len(train_acc_list)):
  train_err_list.append(100 - train_acc_list[i])
  val_err_list.append(100 - val_acc_list[i])
  # test_err_list.append(100 - test_acc_list[i])

axes[1].plot(epoch, train_err_list, label='train err')
axes[1].plot(epoch, val_err_list, label='val err')
# axes[1].plot(epoch, test_err_list, label='test err')

# axes[1].set_title('Train & Validation & Test error')
axes[1].set_title('Train & Validation error')
axes[1].set_xlabel('epoch')
axes[1].set_ylabel('error')
axes[1].legend()
axes[1].grid()

plt.show()

test_correct = 0
test_iteration = 0
test_loss = 0

with torch.no_grad():
  for X,Y in test_data_loader:
      X = X.to(device)
      Y = Y.to(device)

      hypothesis = model(X)
      loss = criterion(hypothesis, Y)
      test_correct += (torch.argmax(hypothesis, 1) == Y).sum().item()
      test_loss += loss
      test_iteration += 1
  print(test_correct)
  print(len(test_dataset))
  print(f"Test acc: {test_correct/len(test_dataset)*100}%")

from google.colab import drive

drive.mount('/content/drive')

import json

save_path = '/content/drive/MyDrive/Colab Notebooks/History/CIFAR-10(SAM+SGD) 30epoch.json'

history = {
    'train_loss_list' : train_loss_list,
    'val_loss_list' : val_loss_list,
    # 'test_loss_list' : test_loss_list,
    'train_acc_list' : train_acc_list,
    'val_acc_list' : val_acc_list,
    # 'test_acc_list' : test_acc_list
}

with open(save_path, 'w') as f:
  json.dump(history, f)

torch.save(model.state_dict(), '/content/drive/MyDrive/Colab Notebooks/History/ResNet20_v3.pth')

print('saved')